# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsk-event-listener
  labels:
    app: rsk-event-listener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rsk-event-listener
  template:
    metadata:
      labels:
        app: rsk-event-listener
    spec:
      containers:
      - name: listener
        image: rsk-event-listener:latest
        ports:
        - containerPort: 8080
        env:
        - name: RSK_ENDPOINT
          value: "https://public-node.rsk.co"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rsk-event-listener-service
spec:
  selector:
    app: rsk-event-listener
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer