global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'rsk-event-listener'
    static_configs:
      - targets: ['localhost:8081']  # ✅ Correct port
    metrics_path: /metrics           # ✅ Correct path
    scrape_interval: 10s            # ✅ Good frequency
    scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

