# app:
#   name: "rsk-event-listener"
#   version: "1.0.0"
#   environment: "development"
#   debug: true

# rsk:
#   node_url: "https://public-node.testnet.rsk.co"
#   network_id: 31 # RSK Testnet
#   backup_nodes:
#     - "https://public-node.testnet.rsk.co"
#   request_timeout: "30s"
#   retry_attempts: 3
#   retry_delay: "5s"
#   max_connections: 10

# storage:
#   type: "sqlite" # sqlite or postgres
#   connection_string: "./data/events.db"
#   max_connections: 25
#   max_idle_time: "15m"
#   migrations_path: "./internal/storage/migrations"

# monitor:
#   poll_interval: "15s" # RSK blocks are ~30s, so poll every 15s
#   batch_size: 100
#   confirmation_blocks: 12 # Wait for 12 confirmations
#   start_block: 0 # 0 means start from latest
#   enable_websocket: false # Use polling for MVP
#   max_reorg_depth: 64

# processor:
#   workers: 4
#   queue_size: 1000
#   process_timeout: "30s"
#   retry_attempts: 3
#   retry_delay: "5s"
#   enable_async: true

# notifications:
#   enabled: true
#   queue_size: 100
#   workers: 2
#   retry_delay: "10s"
#   max_retries: 3
#   default_channel: "log"

# server:
#   port: 8081
#   host: "0.0.0.0"
#   read_timeout: "10s"
#   write_timeout: "10s"
#   enable_metrics: true
#   enable_health: true

# logging:
#   level: "info" # debug, info, warn, error
#   format: "json" # json or text
#   output: "stdout" # stdout or file
#   file: "./logs/app.log"
#   max_size: 100 # MB
#   max_backups: 3
#   max_age: 28 # days

# File: config/config.yaml
# RSK Event Listener Configuration

app:
  name: "rsk-event-listener"
  version: "1.0.0"
  environment: "development"
  debug: false

rsk:
  node_url: "https://public-node.testnet.rsk.co"
  network_id: 31  # RSK Testnet
  backup_nodes:
    - "https://public-node.testnet.rsk.co"
  request_timeout: "30s"
  retry_attempts: 3
  retry_delay: "5s"
  max_connections: 10

storage:
  type: "sqlite"
  connection_string: "./data/events.db"
  max_connections: 25
  max_idle_time: "15m"
  migrations_path: "./internal/storage/migrations"

monitor:
  poll_interval: "15s"
  batch_size: 100
  confirmation_blocks: 12
  start_block: 0
  enable_websocket: false
  max_reorg_depth: 64

processor:
  workers: 4
  queue_size: 1000
  process_timeout: "30s"
  retry_attempts: 3
  retry_delay: "5s"
  enable_async: true

notifications:
  enabled: true
  queue_size: 100
  workers: 2
  retry_delay: "10s"
  max_retries: 3
  default_channel: "log"

server:
  port: 8081
  host: "0.0.0.0"
  read_timeout: "10s"
  write_timeout: "10s"
  enable_metrics: true
  enable_health: true

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file: ""
  max_size: 100
  max_backups: 3
  max_age: 28