notification:
  max_concurrent_notifications: 5
  notification_timeout: 10s
  retry_attempts: 3
  retry_delay: 2s
  enable_email_notifications: true
  enable_webhook_notifications: true
  queue_size: 500
  log_level: "info"

  email:
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"
    from_email: "your-email@gmail.com"
    from_name: "RSK Event Listener"
    use_tls: true
    use_start_tls: true
    timeout: 30s

  channels:
    - id: "slack_alerts"
      name: "Slack Alerts Channel"
      type: "webhook"
      enabled: true
      config:
        url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        format: "slack"
        
    - id: "email_admin"
      name: "Admin Email Notifications"
      type: "email"
      enabled: true
      config:
        recipients: ["admin@example.com"]
        priority: "high"
        
    - id: "webhook_api"
      name: "External API Webhook"
      type: "webhook"
      enabled: true
      config:
        url: "https://api.example.com/webhooks/events"
        method: "POST"
        headers:
          Authorization: "Bearer YOUR_API_TOKEN"
          Content-Type: "application/json"